---
- name: TP Ansible Avance:Deploiement Apache et Securite
  hosts: webservers             # Cible la machine 'apache-cible' dans hosts.ini
  gather_facts: true            # SSH est deja installe, donc on peut collecter les faits.
  become: true                  # Necessaire pour toutes les taches systeme (apt, service, etc.)
  vars_files:
    - vars/site_vars.yml        # Importe les variables dynamiques

  tasks:
    # 1. INSTALLATION APACHE
    - name: 1. Installation du paquet Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: 2. Demarrer Apache2 via la commande binaire
      ansible.builtin.command: /usr/sbin/apache2ctl start
      # L'option 'changed_when: true' est souvent necessaire pour forcer Ansible a reconnaitre un changement
      # car 'command' ne verifie pas l'idempotence par defaut.
      changed_when: true

    # 2. DEPLOIEMENT DYNAMIQUE DU CONTENU
    - name: 3. Creer une page d'accueil personnalisee (Template)
      # Utilise le template pour generer le contenu HTML avec les variables Jinja2
      ansible.builtin.template:
        src: files/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'

    # 3. GESTION DE LA CONFIGURATION AVANCEE
    - name: 4. Configurer la securite du serveur (Template)
      # Genere le fichier de configuration de securite Apache a partir d'un template
      ansible.builtin.template:
        src: files/security.conf.j2
        dest: /etc/apache2/conf-available/security.conf
        owner: root
        group: root
        mode: '0644'
      notify:                   # Declenche le Handler 'Redemarrer Apache' si le fichier change
        - Redemarrer Apache

    - name: 5. Activer le fichier de configuration de securite
      # Execute la commande systeme a2enconf pour activer la nouvelle configuration
      ansible.builtin.command: a2enconf security
      changed_when: '"Enabling conf" in deploy_conf_result.stdout' # Rend cette tache idempotente
      register: deploy_conf_result
      notify:
        - Redemarrer Apache

  handlers:
    - name: Redemarrer Apache
      ansible.builtin.command: /usr/sbin/apache2ctl restart
      # Le redemarrage est necessaire, donc on considere qu'il change l'etat
      changed_when: true
